server:
  port: 5000
  # 1. Trust the CloudFront headers so redirects use "https://"
  forward-headers-strategy: framework
  
  servlet:
    context-path: /api
    session:
      cookie:
        # 2. Force the cookie to be Secure (HTTPS only)
        secure: true
        # 3. Allow the cookie to travel between Frontend & Backend domains
        same-site: none
        # 4. (Optional) Ensure the cookie isn't accessible via JavaScript
        http-only: true

spring:
    application:
        name : hotelreservationsystem
    data:
        mongodb:
            uri: ${MONGO_DB}
    output:
        ansi:
            enabled: always
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        # What info we want from the user
                        scope:
                        - openid
                        - profile
                        - email
                        # This must match what you put in Google Cloud Console
                        redirect-uri: ${GOOGLE_REDIRECT_URI}
                        client-name: Google
    mail:
        host: smtp.gmail.com
        port: 587
        username: anthonyhugginsdev@gmail.com
        # Wrap the password in quotes because it contains spaces
        password: ${GMAIL_APP_PASSWORD} 
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

stripe:
    key: ${STRIPE_SECRET}

aws:
    region: us-east-1
    s3:
        bucket: 20251117-ey-project2-group4-assets

app:
  cors:
    # This grabs the value from the 'FRONTEND_URL' env var in Elastic Beanstalk
    allowed-origins: ${FRONTEND_URL}